//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Defects = new HashSet<Defect>();
            this.Releases = new HashSet<Release>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
    
        public virtual ICollection<Defect> Defects { get; set; }
        public virtual ICollection<Release> Releases { get; set; }
    }
}
