//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release
    {
        public Release()
        {
            this.Defects = new HashSet<Defect>();
        }
    
        public int Id { get; set; }
        public int Prod_Id { get; set; }
        public string Product_Name { get; set; }
    
        public virtual ICollection<Defect> Defects { get; set; }
        public virtual Product Product { get; set; }
    }
}
